name: Compile and Release LaTeX Document
on:
  push:
    branches: [ master ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Dissertation.tex

      - name: Create Release and Upload Asset
        id: create_release_and_upload_asset
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          draft: false
          prerelease: false
          files: Dissertation.pdf
          fail_on_unmatched_files: true
          tag_name: Release ${{ github.event.head_commit.timestamp }} - ${{  github.ref }}
